### select rivers in hma

In [1]:
import numpy as np
import geopandas as gpd

#### Select major rivers in hma from global rivers.

In [2]:
path_rivers_global = 'data/rivers/global_major_rivers.gpkg'

#### Note:   
-- Yarlung Zangbo also know as Brahmaputra;   
-- Nu Jiang also know as Salween;   
-- Chang Jiang also know as Yangtze River.

In [4]:
### Check data
rivers_global = gpd.read_file(path_rivers_global)
print(rivers_global.shape)
rivers_global.head(2)

(98, 5)

,NAME,SYSTEM,MILES,KILOMETERS,geometry
0,Kolyma,NaN,2551.51838,4106.27900,"MULTILINESTRING ((144.84189 61.75915, 144.8257..."
1,Parana,Parana,1616.20622,2601.03698,"MULTILINESTRING ((-51.0064 -20.07941, -51.0297..."

In [6]:
### Rivers in hma
rivers_hma = ['Indus', 'Ganges', 'Yarlung Zangbo', 'Mekong', 'Irrawaddy', 'Huang He', \
              'Syr Darya', 'Amu Darya', 'Chang Jiang', 'Xi Jiang', 'Nu Jiang']
ids = [np.where(rivers_global.NAME==name)[0].item() for name in rivers_hma]
rivers_hma = rivers_global.loc[ids]
print(rivers_hma.shape)
rivers_hma.head()

(11, 5)

,NAME,SYSTEM,MILES,KILOMETERS,geometry
57,Indus,NaN,2015.16218,3243.09564,"MULTILINESTRING ((67.48645 24.04542, 67.65091 ..."
56,Ganges,NaN,1481.59615,2384.40264,"MULTILINESTRING ((79.87328 30.95868, 79.81163 ..."
55,Yarlung Zangbo,NaN,1897.09807,3053.08950,"MULTILINESTRING ((82.00998 30.48415, 82.24191 ..."
62,Mekong,NaN,2942.45095,4735.42525,"MULTILINESTRING ((93.88553 33.26776, 93.88915 ..."
61,Irrawaddy,NaN,1297.67231,2088.40532,"MULTILINESTRING ((94.98852 16.23617, 95.12437 ..."

In [ ]:
# ### Write out
# rivers_hma.to_file('data/rivers/hma_major_rivers.gpkg', driver='GPKG')